### ISSUE TITLE
Unable to find various metal files

### ISSUE THREAD

**Issue by hoyinchow** [Robert-Frampton/liferay-theme-es2015-hook#1]
After creating a Liferay theme using yo liferay-theme, modifying various files etc etc [the exact steps can be found in Liferay University under the front end developer course. Download the slides and exercise materials and the actual procedure can be found in folder 03 theme developerment -> 02-generating-themes.pdf]

After running `npm i -save liferay-theme-es2015 hook` and modifying the `package.json` file, I get the following error (see image attached), I've also attached the `package.json` in a zip file. If there is any other details that you need just let me know.

![liferay-es2015-pic](https://cloud.githubusercontent.com/assets/4844287/20204618/52188b9e-a786-11e6-9c80-48d1b5db0978.PNG)
[package.zip](https://github.com/Robert-Frampton/liferay-theme-es2015-hook/files/585032/package.zip)

**Comment by jromahen** [comment]
@Robert-Frampton @hoyinchow I went through it this morning again, and realised that we had added the `metal`, `metal-dom`, and `metal-state` dependencies without having the npm packages installed.  

As soon as I installed the packages through `npm`, everything worked just fine.

**Comment by robframpton** [comment]
👍
