### ISSUE TITLE
NPM publish permissions

### ISSUE THREAD

**Issue by jbalsas** [Robert-Frampton/liferay-theme-es2015-hook#6]
Can I get permissions to publish this module too, pretty pretty pleeease? 🙏

**Comment by natecavanaugh** [comment]
@robframpton Could you transfer ownership of this module to me or Chema or add us as collaborators on NPM?

Thanks Rob :)

**Comment by robframpton** [comment]
Transferred the repo to Chema, added you both to npm 👍

**Comment by jbalsas** [comment]
Thanks! :)
